import Modal from "@/components/Modal";
import "./globals.css";

export const metadata = {
  title: "KeepItUp",
  description: "Generated by Ritik",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/logo-icon.png" sizes="any" />
      </head>
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
